apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: alexnginx
  namespace: second-config
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: alexnginx
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alexnginx
  name: alexnginx
  namespace: second-config
spec:
  containers:
  - image: nginx:alpine
    name: alexnginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
