apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: alexnginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: alexnginx
status:
  loadBalancer: {}
